#0 for standard_deviation creates a Boolean value.
---
config:
  - name: Total_Runtime
    description: The amount of runtime each forecast takes, in minutes.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        bad_data_rate: 0.02
        missing_data_rate: 0.05
        median: 60
        standard_deviation: 7.5
        minimum: 0
        maximum: 120
        backfill_range_hours: 720
        backfill_interval_hours: 6
        backfill_starting_hour: 0
  - name: I_O_Fraction
    description: The ratio of time spent in input to time spent in output.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        bad_data_rate: 0.02
        missing_data_rate: 0.05
        median: 10
        standard_deviation: 3
        minimum: 0
        maximum: 100
        backfill_range_hours: 720
        backfill_interval_hours: 6
        backfill_starting_hour: 0
  - name: Initial_RMS_pressure_tendency
    description: The initial RMS pressure tendency.
    type: gauge
    sequence:
      - eval_time: 1
        interval: 5
        bad_data_rate: 0.02
        missing_data_rate: 0.05
        median: 0.8
        standard_deviation: 0.1
        minimum: 0
        maximum: 2
        backfill_range_hours: 720
        backfill_interval_hours: 6
        backfill_starting_hour: 0
live_mode: False